### PR TITLE
Fix flakey kafka tests

### LINKED ISSUE #295: Kafka tests are flakey
`[info] KafkaSink
[info] - should write messages to a kafka topic *** FAILED ***
[info]   0 was not equal to 10 (KafkaSinkSpec.scala:63)`

### PR DESCRIPTION
**Pull request by BenFradet**
fixes #295

### CODE REVIEW

**Comment by BenFradet** [comment]
I'm suspecting the problem comes from the poll timeout so I'll check what jenkins has to say ~10 times.

**Comment by pankajroark** [comment]
LGTM

**Comment by BenFradet** [comment]
I'll do a few other tests tonight and try to see if it still behaves.

**Comment by BenFradet** [comment]
@johnynek ran the different suites 10 times, not a single kafka-related test is failing.
Tell me when you want me to rebase.

**Comment by johnynek** [comment]
yes, rebase and we'll merge!

**Comment by BenFradet** [comment]
@johnynek done

**Comment by BenFradet** [comment]
pinging @johnynek just in case this slipped through the cracks :open_mouth:

**Comment by johnynek** [comment]
yep. Sorry. Thanks for reminding me.

**Pull request merged**
