### PR TITLE
Cleanup storehaus-caliper

### LINKED ISSUE #281: storehaus-caliper does not compile
Due to a recent refactor, storehaus-caliper fails to compile with the following error:
```
[error] /Users/skrishnan/Projects/storehaus/storehaus-caliper/src/main/scala/com/twitter/storehaus/caliper/WriteThroughCacheBenchmark.scala:65: not found: type HHFilteredStore
[error]     store = (new WriteThroughStore(delayedStore, new HHFilteredStore(new ConcurrentHashMapStore[Long, HLL]), true)).toMergeable
[error]                                                      ^
[error] one error found
```

Looks like we aren't building storehaus-caliper on Travis - hence, we didn't discover this earlier.

### PR DESCRIPTION
**Pull request by BenFradet**
Fixes #281 
Closes #307

### CODE REVIEW

**Comment by BenFradet** [comment]
As I said in #307, should we add storehausCaliper in build.sbt so that it gets compiled by travis as well?

**Comment by johnynek** [comment]
yeah, it would be great to at least build it in travis to prevent bitrot.

**Comment by BenFradet** [comment]
Ok, will do.

**Comment by BenFradet** [comment]
Done :+1:

**Comment by johnynek** [comment]
I think we need to exclude caliper from the mima check (and probably also not publish it)

**Comment by BenFradet** [comment]
Woops, I thought it'd get the same treatment as storehaus-testing but I didn't realize storehaus-testing was published, I'll check that out tomorrow.

**Comment by BenFradet** [comment]
erf maven.twttr.com 503'd during the build causing it to fail :disappointed:

**Comment by johnynek** [comment]
restarting the build

**Comment by BenFradet** [comment]
same thing happened again apparently

**Comment by BenFradet** [comment]
@johnynek could you trigger a new buld? Thanks.

**Comment by johnynek** [comment]
@BenFradet Thanks as always!

**Pull request merged**
