### PR TITLE
Replace usage of deprecated util conversion methods.

### PR DESCRIPTION
**Pull request by kevinoliver**
Problem

As of util commit https://github.com/twitter/util/commit/ee56e5f2418d5d6540d37268436ff6f47520edaf the conversions are deprecated.

Solution

Avoid these conversion methods.

### CODE REVIEW

**Review by johnynek — APPROVED** [review]

**Comment by kevinoliver** [comment]
fwiw looks like CI failed for unrelated [reasons](https://travis-ci.org/twitter/storehaus/jobs/467759495).

```
$ mongo mydb_test --eval 'db.addUser("travis", "test");'
MongoDB shell version v3.4.10
connecting to: mongodb://127.0.0.1:27017/mydb_test
MongoDB server version: 3.4.10
2018-12-13T22:57:17.594+0000 E QUERY    [thread1] TypeError: db.addUser is not a function :
@(shell eval):1:1
The command "mongo mydb_test --eval 'db.addUser("travis", "test");'" failed and exited with 252 during .
```

**Comment by dieu** [comment]
@kevinoliver could you rebase on latest `develop`?

**Comment by dieu** [comment]
```
[info] Compiling 16 Scala sources to /home/travis/build/twitter/storehaus/storehaus-core/target/scala-2.11/test-classes...
[error] /home/travis/build/twitter/storehaus/storehaus-core/src/test/scala/com/twitter/storehaus/RetryingReadableStoreProperties.scala:41: not found: value Duration
[error]         backoffs = for (i <- 0 until 3) yield Duration.fromMilliseconds(1)
[error]      
```
@kevinoliver compilation is falling.

**Comment by dieu** [comment]
@kevinoliver thanks for your PR.

**Pull request merged**
