### PR TITLE
Fixed storehaus-caliper compilation

### LINKED ISSUE #281: storehaus-caliper does not compile
Due to a recent refactor, storehaus-caliper fails to compile with the following error:
```
[error] /Users/skrishnan/Projects/storehaus/storehaus-caliper/src/main/scala/com/twitter/storehaus/caliper/WriteThroughCacheBenchmark.scala:65: not found: type HHFilteredStore
[error]     store = (new WriteThroughStore(delayedStore, new HHFilteredStore(new ConcurrentHashMapStore[Long, HLL]), true)).toMergeable
[error]                                                      ^
[error] one error found
```

Looks like we aren't building storehaus-caliper on Travis - hence, we didn't discover this earlier.

### PR DESCRIPTION
**Pull request by BenFradet**
fixes #281

### CODE REVIEW

**Comment by BenFradet** [comment]
@johnynek should we add `storehausCaliper` in [build.sbt](https://github.com/twitter/storehaus/blob/develop/build.sbt#L146) so that it gets compiled by travis as well?

**Comment by BenFradet** [comment]
It seems there is a conflict between hbase's zk and kafka's when the two suites are run simultaneously.
I'll investigate.

**Comment by johnynek** [comment]
Great thanks for looking at this!

**Comment by BenFradet** [comment]
From what I've gathered in #308 , we'll need to upgrade hbase in order to force the port (I've been meaning to upgrade storehaus-hbase anyway).
Anyway, should we put storehaus-caliper in the build?

**Pull request closed without merging**
