### PR TITLE
ElasticSearch test is flakey

### LINKED ISSUE #296: ElasticSearch test is flakey
`[info] ElasticSearchStoreSpecs:
[info] ElasticSearch Store
[info] - should Put a value *** FAILED ***
[info]   None did not equal Some(Person(Joe,Smith,29)) (ElasticSearchStoreSpecs.scala:52)`

### PR DESCRIPTION
**Pull request by BenFradet**
fixes #296

### CODE REVIEW

**Comment by BenFradet** [comment]
I increased the timeout, I'll see if it had an impact by running the suites ~10 times.

**Comment by johnynek** [comment]
@BenFradet looks like you got it!

I guess the less is, timeouts should be giant on travis.

**Comment by johnynek** [comment]
ready to merge?

**Comment by BenFradet** [comment]
I'm gonna do a few more first but I feel pretty confident.
I'll ping you when I'll be good to go.

**Comment by BenFradet** [comment]
@johnynek ran it successfully 10 times and I'm ready to go!

**Comment by johnynek** [comment]
awesome!

**Pull request merged**
