### PR TITLE
Update finagle and other twitter deps to 2019 compatible versions.

### PR DESCRIPTION
**Pull request by cacts**
The (still unreleased) develop version of storehaus is not binary compatible with the current versions of Finagle. This PR updates them to recent versions by using the twitter Bufs provided in the new finagle-x clients, and removes ChannelBuffers which were obsoleted with the release of netty 4.

### CODE REVIEW

**Comment by johnynek** [comment]
thanks for the PR, if we can get this green, I'll merge it.

**Comment by cacts** [comment]
thanks @johnynek!  looks like i've finally got it fixed up.

edit: the mima previous versions will have to be uncommented after an artifact is published.

**Comment by jho** [comment]
Any chance we can get this merged?

**Comment by cacts** [comment]
@johnynek mind having a look at this?

**Pull request closed without merging**
