### PR TITLE
Remove mutex from ReadThroughStore and WriteThroughStore.

### PR DESCRIPTION
**Pull request by ielashi**
Reasons for removing the mutex:

    1) It severely limits throughput.

    2) There is nothing about Read/WriteThroughStore that is not
       thread-safe. If it's to keep the data stores thread-safe, then it should
       be the data store's responsibility to do so.

    3) If adding the mutex is to avoid race conditions, a mutex also doesn't
       protect against that if you have multiple clients.

### CODE REVIEW

**Comment by johnynek** [comment]
Seems reasonable, but this does not merge cleanly. Can you rebase against develop?

**Comment by ielashi** [comment]
Updated to resolved conflict.

**Comment by sritchie** [comment]
Works for me. Thanks @ielashi !

**Comment by ielashi** [comment]
@sritchie Thanks for merging! May I request we do a release with this change?

**Pull request merged**
